### ISSUE TITLE
Missing `htmlSafe` and `isHTMLSafe`

### ISSUE THREAD

**Issue by gentoid** [emberjs/ember-string#235]
After bumping Ember to 3.24 in our project I got the following errors:

```
node_modules/@types/ember/index.d.ts:446:46 - error TS2339: Property 'htmlSafe' does not exist on type 'typeof import("C:/Users/.../node_modules/@ember/string/index")'.

446         const htmlSafe: typeof EmberStringNs.htmlSafe;
                                                 ~~~~~~~~

node_modules/@types/ember/index.d.ts:447:48 - error TS2339: Property 'isHTMLSafe' does not exist on type 'typeof import("C:/Users/.../node_modules/@ember/string/index")'.

447         const isHTMLSafe: typeof EmberStringNs.isHTMLSafe;
                                                   ~~~~~~~~~~
```
(and a screenshot of the errors if this is helpful)

![image](https://user-images.githubusercontent.com/232243/103937282-d7714b00-5128-11eb-95cb-b4268f08831e.png)

Interestingly enough, this package exposes TS definitions, and also there're definitions at `@types/ember__string`. And [the latter](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/ember__string/index.d.ts) does expose `htmlSafe` and `isHTMLSafe`

**Comment by gentoid** [comment]
Oh, this topic was even raised once, in #217. But no new releases were since then, so obviously removing of `node_modules` didn't help. Do you by any chance plan to release new version soon?

**Comment by ef4** [comment]
This continues to be a serious hazard for apps.

The problem is that an addon can pull this package into the build, and it can break an unrelated addon that was relying on the deprecated methods.

**Comment by kategengler** [comment]
I added versions of these methods that error with explanation in https://github.com/emberjs/ember-string/pull/367
